### ISSUE TITLE
KillAura/Forcefield

### ISSUE THREAD

**Issue by Shyrogan** [MizuClarinet/client#1]
### Meta data

ID: `kill_aura` or `force_field`
Toggleable

Attacks surrounding entities if they are considered as hostile. That includes end crystals.

### Settings

`mode`: Modifies the overall behavior of the module
1. `single`: Finds the best target and focus him.
2. `switch`: Switches every `maximum_hits` hits the target, if there are multiple targets available.
  - `max_hits`: The amount of hits the module hits before switching.
3. `multi`: Hits multiple entities at the same time.
  - `max_targets`: The amount of targets that can be hit in a single attack.

`aps`: The range of attack per seconds allowed.
- `maximize_strength`: For 1.8+ servers, we have to actually figure out the best moment to actually hit the player. `aps` is only used as a "maximum" value.

`range`: The maximum distance between the client player and the target.
- `infinite`: Forces the module the ignore `range` value and teleport to the player for every hit.

`priority`: Sorts the entities to focus them based on different criteria.
- `sort_type`: Defines whether
  1. `ascending`: The lower the value, the first attacked
  2. `descending`: The higher the value, the first attacked
1. `armor`
2. `health`
3. `weapon`

`ignore_invisible`: Ignores invisible players

**Comment by Shyrogan** [comment]
This list will be expanded when I'll code the module.

**Comment by Shyrogan** [comment]
Should we put target hud as a setting in this mod?

**Comment by qtdyn** [comment]
TargetHUD as a toggleable setting but actual hud component configuration inside the custom HUD gui or something

**Comment by Shyrogan** [comment]
> TargetHUD as a toggleable setting but actual hud component configuration inside the custom HUD gui or something

😳 could be a good idea
