### ISSUE TITLE
Commands

### ISSUE THREAD

**Issue by Shyrogan** [MizuClarinet/client#6]
Until we have a good looking UI, commands will be used to configure the mods settings/client behavior.
This issue will be used as a list of commands we actually need to implement and will regularly updated.

- [ ] `.send <message>` sends given message in chat.
- [ ] `.toggle <toggleable-mod>` toggles given mod.
- [ ] `.<mod> <setting> <value>` configures given setting (we also need to look into how to configure nested settings)
- [ ] `.config <load|save> <name>` saves/loads given configuration from the local files
- [ ] `.dark` turns on dark mode
- [ ] `.ignore <name>` adds/removes given name to the ignored player list

**Comment by qtdyn** [comment]
Ideas:
`.send` aliases `.say`
`.dark` aliases `.ui theme dark`?
also maybe not `.<mod>` because that'd be emphasizing that Modules are the primary Feature, which there could be other important ones, like `.friend`, although `.mod <name>` would be quite a handful

**Comment by Shyrogan** [comment]
> Ideas:
> `.send` aliases `.say`
> `.dark` aliases `.ui theme dark`?
> also maybe not `.<mod>` because that'd be emphasizing that Modules are the primary Feature, which there could be other important ones, like `.friend`, although `.mod <name>` would be quite a handful

"Friends" will refer to friends in Mizu’s social features.
"mod" would be a painful keyword to use everytime imo but we should discuss it with @milse113 and @lambdagg.

I agree with the others ideas
