### ISSUE TITLE
X-Ray

### ISSUE THREAD

**Issue by lambdagg** [MizuClarinet/client#8]
### **Metadata**

ID: xray
Toggleable

Hide non-ore blocks.

### **Settings**

- `mode`: Some servers have (more than unviable) solutions against xray, for example the Paper Spigot fork has a built-in anti-xray that sends random blocks in the other chunks than those which you are in.

- `opacity`: (@Shyrogan) We don't need a fully transparent X-Ray in minigames.

### Ideas

Maybe we could add a seed cracker and then predict all ores for a given chunk?

**Comment by Shyrogan** [comment]
Opacity would be nice setting to have, in minigames we don’t need a fully transparent X-ray.

Implementing new culling calculations would also be a good thing yet I dunno how to do it efficiently.

Seed cracker could be nice but génération changed a lot and we would have to implement all versions.

**Comment by lambdagg** [comment]
> Seed cracker could be nice but génération changed a lot and we would have to implement all versions.

That may be the kind of feature to be implemented later, when the first release rolls out.

**Comment by Shyrogan** [comment]
I'll add x-ray to the first version milestone yet seed cracker and other advanced x-ray calculations will be done in future versions.
